# Generated by Django 2.1.7 on 2019-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Biodata', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=10, unique=True)),
                ('Social', models.CharField(max_length=100)),
            ],
        ),
    ]
